version: "3.8"

services:
  # yb-standalone is the db used for measures and metrics
  yb-standalone:
      image: yugabytedb/yugabyte:latest
      logging: 
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "10m"
      container_name: yb-standalone
      volumes:
      - "${HOME}/tmp/yb_data:/home/yugabyte/yb_data"
      command: sh -c "/home/yugabyte/bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false --ui=false"
      # The local ports are assigned dynamically. If you want to set them for your environment use "7000:7000" (or "70001:7000" etc)
      ports:
      - ":7000"
      - ":9000"
      - ":5433"
      - ":9042"

  # caml_dev is a working development/test environment
  caml_dev:
      # TODO: explore is env_file is the best way to setup CLI git toolchain
      # modify this file to pass environment variables into the container
      # env_file: ../../github.env
      build:
        context: .
        dockerfile: Dockerfile.caml_dev
        # the $GITREPO value is coming from .env located in the same
        # directory as this yaml file. It will look something like (make it point to your fork): 
        #   prompt% cat Docker/.env
        #   GITREPO=https://github.com/ContiNube/CAML.git
        # TODO: see about explicitly indicating this file instead of depending on the hidden dot file "sideeffect" 
        args:
          - gitrepo=$GITREPO
      image: caml_dev
      container_name: caml_dev
      tty: true
#networks:
#  default:
#    external:
#       name: caml_default
#  internal:
#    external:
#      name: caml_internal
volumes:
  yb-master-data-1:
  yb-tserver-data-1:

