# this dockerfile establishes a single build/run environment for
# all the elements of CAML source distribution. For simplicity this
# is a single environment for /src stuff.  

# go being the lingua in question we start with a golang image so 
# supporting dev work in place is easy
# NOTE: There appears to be a recent problem building node_exporter on the latest golang
# ref: https://stackoverflow.com/questions/71758856/github-action-for-golangci-lint-fails-with-cant-load-fmt from 9 days ago
# TODO: determine process for updating to latest w/o risking random failures
FROM golang:1.17.7 as prepit

# build a working image by installing git tooling and cloning the repo
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y yamllint
WORKDIR /go/src

# $gitrepo is the Continuous Audit Metrics Library repo
# $gitrepo needs to be passed in as a --build-arg 
# or set via docker-compose.caml_dev.yaml
ARG gitrepoCAML
RUN git clone $gitrepoCAML

# $gitrepocam is the CSA Continuous Audit Metrics repo
# set this the same way as you set $gitrep
ARG gitrepoCAM
RUN git clone $gitrepoCAM

# at this point a developer can attach vscode to the dev image and work with it directly
# to do so:
#       - attach vscode to the running image
#       - follow the prompts to install their dev environment stuff (for building and debugging)
#       - when you first try to commit changes it will walk you through obtaining authorization tokens
#         at the vscode level to enable a push.
# TODO: explore gitlens extention 
# TODO: explore ensuring CLI git is configured automatically. because git is installed as per the above it works but you'll be forced to put your authorization token into the container which is not recommended. Better to just use the vscode model if thats an option.

FROM prepit as buildit

# CAML toolchain
WORKDIR /go/src/CAML/src/main
RUN go mod download
RUN go mod tidy -compat=1.17 && \
    go get -d -v 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o camldataservice .

# in order to integrate with openmetrics/prometheus 
# install prometheus node_collector
# NOTE: node_collector's primary purpose is collecting information about the 'node'/instance. We're not using it for that. Instead we're leveraging https://github.com/prometheus/node_exporter/blob/master/README.md#textfile-collector 
# TODO: no attempt was made here to keep the resulting image small. that should be done. 
WORKDIR /go/src
RUN git clone https://github.com/prometheus/node_exporter
WORKDIR /go/src/node_exporter
# RUN make

WORKDIR /go/src
COPY caml_dev_wrapper_script.sh caml_dev_wrapper_script.sh
RUN ["chmod", "+x", "caml_dev_wrapper_script.sh"]
CMD ./caml_dev_wrapper_script.sh
